In [1]:
import pandas as pd                      #data frame library.csv,excel file import by pandas.csv create by pandas.
import numpy as np                       #mathemathecal library.need for linear algebra,large array.
from matplotlib import pyplot as plt     #data visualization libraray.use to draw plot,graph.

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
df = pd.read_excel("/content/drive/MyDrive/Height-Width.xlsx")          #load dataset


In [5]:
df.head()

Height      Weight
0  73.847017  241.893563
1  68.781904  162.310473
2  74.110105  212.740856
3  71.730978  220.042470
4  69.881796  206.349801

In [6]:
df.shape

(3501, 2)

In [7]:
df.isnull().sum()

Height    0
Weight    0
dtype: int64

In [8]:
x = df[['Height']]

In [9]:
x.head()

Height
0  73.847017
1  68.781904
2  74.110105
3  71.730978
4  69.881796

In [10]:
y=df['Weight']

In [11]:
y.head()

0    241.893563
1    162.310473
2    212.740856
3    220.042470
4    206.349801
Name: Weight, dtype: float64

In [12]:
from sklearn.model_selection import train_test_split as tts

In [13]:
xtrain,xtest,ytrain,ytest = tts(x,y,test_size=0.3,random_state=5)

In [14]:
xtrain.head()

Height
3466  67.172828
828   66.653234
2234  65.077902
3245  65.035786
1298  69.702258

In [15]:
from sklearn.linear_model import LinearRegression

In [16]:
reg = LinearRegression()

In [17]:
reg.fit(xtrain,ytrain) #data gulo ke train kora hoi fit function dara. linear regression algo tar sahajje machine ke train korailam fit dara.

LinearRegression()

In [18]:
m = reg.coef_    #y= mx + c

In [19]:
m


array([6.00809929])

In [20]:
c = reg.intercept_


In [21]:
c

np.float64(-227.77595602223434)

In [23]:
import warnings
warnings.filterwarnings("ignore")  # This code disables all warning messages in Python, often used in ML to keep output clean.


In [24]:
reg.predict([[3000]])

array([17796.52189924])

In [25]:
pred = reg.predict(xtest)
pred

array([156.22895255, 171.26045447, 186.87942774, ..., 205.60020285,
       186.14253731, 219.24585226])

In [26]:
df["Predicted Result"] = reg.predict(x) # new colom add

In [27]:
df.head()

Height      Weight  Predicted Result
0  73.847017  241.893563        215.904254
1  68.781904  162.310473        185.472553
2  74.110105  212.740856        217.484915
3  71.730978  220.042470        203.190884
4  69.881796  206.349801        192.080812

In [28]:
from sklearn.metrics import mean_absolute_error, mean_squared_error #error ber kora....yt dia concept clear korte hbe error mane asole ki...

In [29]:
mse = mean_squared_error(ytest,pred) # ytest = actual result(data),pred = predict resulr(ber kora data)

In [30]:
mse


102.60138482843213

In [31]:
mae = mean_absolute_error(ytest,pred)
mae

8.061150778858023

In [32]:
from sklearn.metrics import r2_score  # accuracy by r2_score
r2_score(ytest,pred)

0.7302328605746943

In [33]:
import pickle
import joblib

In [35]:
# 8) Save model using pickle
with open("linear_regression_height_to_width.pkl", "wb") as f:
    pickle.dump(reg, f)

# 9) Save model using joblib
joblib.dump(reg, "linear_regression_height_to_width.joblib")

print("Model saved using both pickle and joblib.")

Model saved using both pickle and joblib.


In [36]:
import pickle, joblib
import numpy as np

# Pickle load
with open("linear_regression_height_to_width.pkl", "rb") as f:
    model_pickle = pickle.load(f)

# Joblib load
model_joblib = joblib.load("linear_regression_height_to_width.joblib")

# Predict (example height = 70)
height_val = np.array([[70]])
print(model_pickle.predict(height_val))
print(model_joblib.predict(height_val))


[192.79099393]
[192.79099393]


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

import pickle
import joblib

# 1) Load dataset
df = pd.read_excel("Height-Width.xlsx")  # update path if needed

# NOTE: File columns are Height and Weight.
# Treating Weight as "Width" to match your task.
X = df[['Height']].values
y = df['Weight'].values

# 2) Split data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# 3) Train Linear Regression
model = LinearRegression()
model.fit(X_train, y_train)

# 4) Predict
y_pred = model.predict(X_test)

# 5) Metrics
r2 = r2_score(y_test, y_pred)                 # accuracy (R^2)
mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)

print("Accuracy (R2):", r2)
print("MSE:", mse)
print("MAE:", mae)

# 6) Best fit line equation
slope = model.coef_[0]
intercept = model.intercept_
print(f"Best Fit Line: Width = {slope:.6f} * Height + {intercept:.6f}")

# 7) Plot best fit line
plt.figure()
plt.scatter(X_test, y_test, alpha=0.35)

x_line = np.linspace(X.min(), X.max(), 200).reshape(-1, 1)
y_line = model.predict(x_line)

plt.plot(x_line, y_line)
plt.xlabel("Height")
plt.ylabel("Width (Weight column)")
plt.title("Linear Regression: Width vs Height")
plt.savefig("best_fit_line.png", dpi=200, bbox_inches="tight")
plt.show()

# 8) Save model using pickle
with open("linear_regression_height_to_width.pkl", "wb") as f:
    pickle.dump(model, f)

# 9) Save model using joblib
joblib.dump(model, "linear_regression_height_to_width.joblib")

print("Model saved using both pickle and joblib.")


In [ ]:
import pickle, joblib
import numpy as np

# Pickle load
with open("linear_regression_height_to_width.pkl", "rb") as f:
    model_pickle = pickle.load(f)

# Joblib load
model_joblib = joblib.load("linear_regression_height_to_width.joblib")

# Predict (example height = 70)
height_val = np.array([[70]])
print(model_pickle.predict(height_val))
print(model_joblib.predict(height_val))
